// Assignment 2
// week 3
// DIY projects

/* Main.ino file generated by New Project wizard
 *
 * Created:   Thu Sep 5 2013
 * Processor: ATmega328P
 * Compiler:  Arduino AVR
 */

void setup()
 { 
   pinMode(13,OUTPUT);
   Serial.begin(9600);
 }

void loop()
 { 
 digitalWrite(13,HIGH);
 delay(500);
 digitalWrite(13,LOW);
 delay(1000);
 
 digitalWrite(13,HIGH);
 delay(250);
 digitalWrite(13,LOW);
 delay(500);
 
 digitalWrite(13,HIGH);
 delay(2000);
 digitalWrite(13,LOW);
 delay(4000);
 

 
 }
